In [1]:
import numpy as np
import pandas as pd

## Object creation
Creating a `Series` by passing a list of values, letting pandas create a default integer index:

In [2]:
s = pd.Series([1, 3, 5, np.nan, 6, 8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

Creating a `DataFrame` by passing a NumPy array, with a datetime index and labeled columns:

In [3]:
dates = pd.date_range('20200105', periods=6)
dates

DatetimeIndex(['2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [4]:
df = pd.DataFrame(np.random.randn(6, 4), index=dates, columns=list('ABCD'))
df

A         B         C         D
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

Creating a `DataFrame` by passing a dict of objects that can be converted to series-like.

In [5]:
df2 = pd.DataFrame({'A': 1.,
                    'B': pd.Timestamp('20200106'),
                    'C': pd.Series(1, index=list(range(4)), dtype='float32'),
                    'D': np.array([3] * 4, dtype='int32'),
                    'E': pd.Categorical(["happy", "new", "year", "yeah"]),
                    'F': 'foo'})
df2

A          B    C  D      E    F
0  1.0 2020-01-06  1.0  3  happy  foo
1  1.0 2020-01-06  1.0  3    new  foo
2  1.0 2020-01-06  1.0  3   year  foo
3  1.0 2020-01-06  1.0  3   yeah  foo

The columns of the resulting DataFrame have different dtypes.

In [6]:
df2.dtypes

A           float64
B    datetime64[ns]
C           float32
D             int32
E          category
F            object
dtype: object

use tab to prompt
> df2.<TAB>  # noqa: E225, E999

## Viewing data

In [7]:
df.head(3)

A         B         C         D
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347

In [8]:
df.tail(3)

A         B         C         D
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

In [9]:
df.index

DatetimeIndex(['2020-01-05', '2020-01-06', '2020-01-07', '2020-01-08',
               '2020-01-09', '2020-01-10'],
              dtype='datetime64[ns]', freq='D')

In [10]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

In [11]:
df.values

array([[-0.52959153,  0.8139254 , -0.96729652, -0.14951377],
       [ 0.05409598, -1.84621578, -1.27381429,  1.8105444 ],
       [ 0.39106887, -0.65476392,  0.88361314,  1.12834739],
       [-0.40310939, -0.69662847, -0.47627511,  0.33876378],
       [ 0.32225072, -0.42379884, -0.18672311,  0.69028133],
       [ 1.06825722,  1.07143418, -1.91898408, -0.18741355]])

In [13]:
df.to_numpy()

array([[-0.52959153,  0.8139254 , -0.96729652, -0.14951377],
       [ 0.05409598, -1.84621578, -1.27381429,  1.8105444 ],
       [ 0.39106887, -0.65476392,  0.88361314,  1.12834739],
       [-0.40310939, -0.69662847, -0.47627511,  0.33876378],
       [ 0.32225072, -0.42379884, -0.18672311,  0.69028133],
       [ 1.06825722,  1.07143418, -1.91898408, -0.18741355]])

In [12]:
df2.to_numpy()

array([[1.0, Timestamp('2020-01-06 00:00:00'), 1.0, 3, 'happy', 'foo'],
       [1.0, Timestamp('2020-01-06 00:00:00'), 1.0, 3, 'new', 'foo'],
       [1.0, Timestamp('2020-01-06 00:00:00'), 1.0, 3, 'year', 'foo'],
       [1.0, Timestamp('2020-01-06 00:00:00'), 1.0, 3, 'yeah', 'foo']],
      dtype=object)

describe() shows a quick statistic summary of your data:

In [14]:
df.describe()

A         B         C         D
count  6.000000  6.000000  6.000000  6.000000
mean   0.150495 -0.289341 -0.656580  0.605168
std    0.584457  1.077985  0.969191  0.774932
min   -0.529592 -1.846216 -1.918984 -0.187414
25%   -0.288808 -0.686162 -1.197185 -0.027444
50%    0.188173 -0.539281 -0.721786  0.514523
75%    0.373864  0.504494 -0.259111  1.018831
max    1.068257  1.071434  0.883613  1.810544

In [15]:
df2.describe()

A    C    D
count  4.0  4.0  4.0
mean   1.0  1.0  3.0
std    0.0  0.0  0.0
min    1.0  1.0  3.0
25%    1.0  1.0  3.0
50%    1.0  1.0  3.0
75%    1.0  1.0  3.0
max    1.0  1.0  3.0

Transposing your data:

In [16]:
df.T

2020-01-05  2020-01-06  2020-01-07  2020-01-08  2020-01-09  2020-01-10
A   -0.529592    0.054096    0.391069   -0.403109    0.322251    1.068257
B    0.813925   -1.846216   -0.654764   -0.696628   -0.423799    1.071434
C   -0.967297   -1.273814    0.883613   -0.476275   -0.186723   -1.918984
D   -0.149514    1.810544    1.128347    0.338764    0.690281   -0.187414

Sorting by an axis:

In [17]:
df.sort_index(axis=1, ascending=False)

D         C         B         A
2020-01-05 -0.149514 -0.967297  0.813925 -0.529592
2020-01-06  1.810544 -1.273814 -1.846216  0.054096
2020-01-07  1.128347  0.883613 -0.654764  0.391069
2020-01-08  0.338764 -0.476275 -0.696628 -0.403109
2020-01-09  0.690281 -0.186723 -0.423799  0.322251
2020-01-10 -0.187414 -1.918984  1.071434  1.068257

Sorting by values:

In [18]:
df.sort_values(by='B')

A         B         C         D
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

## Selection
### Getting
Selecting a single column, which yields a Series, equivalent to df.A:

In [19]:
df['A']

2020-01-05   -0.529592
2020-01-06    0.054096
2020-01-07    0.391069
2020-01-08   -0.403109
2020-01-09    0.322251
2020-01-10    1.068257
Freq: D, Name: A, dtype: float64

Selecting via [], which slices the rows.

In [20]:
df[1:3]

A         B         C         D
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347

In [21]:
df['20200107': '20200109']

A         B         C         D
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-09  0.322251 -0.423799 -0.186723  0.690281

### Selection by label
For getting a cross section using a label:

In [22]:
df.loc[dates[0]]

A   -0.529592
B    0.813925
C   -0.967297
D   -0.149514
Name: 2020-01-05 00:00:00, dtype: float64

In [23]:
df

A         B         C         D
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

In [24]:
df.loc[dates[0]]

A   -0.529592
B    0.813925
C   -0.967297
D   -0.149514
Name: 2020-01-05 00:00:00, dtype: float64

Selecting on a multi-axis by label:

In [28]:
df.loc[:, ['A', 'B']]

A         B
2020-01-05 -0.529592  0.813925
2020-01-06  0.054096 -1.846216
2020-01-07  0.391069 -0.654764
2020-01-08 -0.403109 -0.696628
2020-01-09  0.322251 -0.423799
2020-01-10  1.068257  1.071434

Showing label slicing, both endpoints are included:

In [29]:
df.loc['20200107': '20200109', ['A', 'B']]

A         B
2020-01-07  0.391069 -0.654764
2020-01-08 -0.403109 -0.696628
2020-01-09  0.322251 -0.423799

Reduction in the dimensions of the returned object:

In [30]:
df.loc['20200106', ['A']]

A    0.054096
Name: 2020-01-06 00:00:00, dtype: float64

For getting a scalar value:

In [31]:
df.loc[dates[0], 'A']

-0.5295915328952078

For getting fast access to a scalar (equivalent to the prior method):

In [32]:
df.at[dates[0], 'A']

-0.5295915328952078

In [ ]:
### Selection by position
Select via the position of the passed integers:

In [33]:
df.iloc[3]

A   -0.403109
B   -0.696628
C   -0.476275
D    0.338764
Name: 2020-01-08 00:00:00, dtype: float64

By integer slices, acting similar to numpy/python:

In [34]:
df.iloc[3:5, 0:2]

A         B
2020-01-08 -0.403109 -0.696628
2020-01-09  0.322251 -0.423799

By lists of integer position locations, similar to the numpy/python style:

In [35]:
df.iloc[[1, 2, 4], [0, 2]]

A         C
2020-01-06  0.054096 -1.273814
2020-01-07  0.391069  0.883613
2020-01-09  0.322251 -0.186723

In [36]:
df.iloc[1:3, :]

A         B         C         D
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347

In [37]:
df.iloc[:, 1:3]

B         C
2020-01-05  0.813925 -0.967297
2020-01-06 -1.846216 -1.273814
2020-01-07 -0.654764  0.883613
2020-01-08 -0.696628 -0.476275
2020-01-09 -0.423799 -0.186723
2020-01-10  1.071434 -1.918984

In [38]:
# For getting a value explicitly:
df.iloc[1,1]

-1.8462157767970178

In [39]:
# For getting fast access to a scalar (equivalent to the prior method):
df.iat[1,1]

-1.8462157767970178

### Boolean indexing
Using a single column’s values to select data.

In [40]:
df[df['A'] > 0]

A         B         C         D
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

Selecting values from a DataFrame where a boolean condition is met.

In [41]:
df[df > 0]

A         B         C         D
2020-01-05       NaN  0.813925       NaN       NaN
2020-01-06  0.054096       NaN       NaN  1.810544
2020-01-07  0.391069       NaN  0.883613  1.128347
2020-01-08       NaN       NaN       NaN  0.338764
2020-01-09  0.322251       NaN       NaN  0.690281
2020-01-10  1.068257  1.071434       NaN       NaN

Using the isin() method for filtering:

In [43]:
df2 = df.copy()
df2['E'] = ['one', 'one', 'two', 'three', 'four', 'three']
df2

A         B         C         D      E
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514    one
2020-01-06  0.054096 -1.846216 -1.273814  1.810544    one
2020-01-07  0.391069 -0.654764  0.883613  1.128347    two
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764  three
2020-01-09  0.322251 -0.423799 -0.186723  0.690281   four
2020-01-10  1.068257  1.071434 -1.918984 -0.187414  three

In [44]:
df2[df2['E'].isin(['one', 'two'])]

A         B         C         D    E
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514  one
2020-01-06  0.054096 -1.846216 -1.273814  1.810544  one
2020-01-07  0.391069 -0.654764  0.883613  1.128347  two

### Setting
Setting a new column automatically aligns the data by the indexes.

In [50]:
s1 = pd.Series(range(1,7), index=pd.date_range('20200106', periods=6))
s1

2020-01-06    1
2020-01-07    2
2020-01-08    3
2020-01-09    4
2020-01-10    5
2020-01-11    6
Freq: D, dtype: int64

In [51]:
df

A         B         C         D
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514
2020-01-06  0.054096 -1.846216 -1.273814  1.810544
2020-01-07  0.391069 -0.654764  0.883613  1.128347
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764
2020-01-09  0.322251 -0.423799 -0.186723  0.690281
2020-01-10  1.068257  1.071434 -1.918984 -0.187414

In [52]:
df['F'] = s1
df

A         B         C         D    F
2020-01-05 -0.529592  0.813925 -0.967297 -0.149514  NaN
2020-01-06  0.054096 -1.846216 -1.273814  1.810544  1.0
2020-01-07  0.391069 -0.654764  0.883613  1.128347  2.0
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764  3.0
2020-01-09  0.322251 -0.423799 -0.186723  0.690281  4.0
2020-01-10  1.068257  1.071434 -1.918984 -0.187414  5.0

In [54]:
df.at[dates[0], 'A'] = 0
df

A         B         C         D    F
2020-01-05  0.000000  0.813925 -0.967297 -0.149514  NaN
2020-01-06  0.054096 -1.846216 -1.273814  1.810544  1.0
2020-01-07  0.391069 -0.654764  0.883613  1.128347  2.0
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764  3.0
2020-01-09  0.322251 -0.423799 -0.186723  0.690281  4.0
2020-01-10  1.068257  1.071434 -1.918984 -0.187414  5.0

In [56]:
df.iat[0, 1] = 0
df

A         B         C         D    F
2020-01-05  0.000000  0.000000 -0.967297 -0.149514  NaN
2020-01-06  0.054096 -1.846216 -1.273814  1.810544  1.0
2020-01-07  0.391069 -0.654764  0.883613  1.128347  2.0
2020-01-08 -0.403109 -0.696628 -0.476275  0.338764  3.0
2020-01-09  0.322251 -0.423799 -0.186723  0.690281  4.0
2020-01-10  1.068257  1.071434 -1.918984 -0.187414  5.0

In [58]:
df.loc[:, 'D'] = np.array([5]* len(df))
df

A         B         C  D    F
2020-01-05  0.000000  0.000000 -0.967297  5  NaN
2020-01-06  0.054096 -1.846216 -1.273814  5  1.0
2020-01-07  0.391069 -0.654764  0.883613  5  2.0
2020-01-08 -0.403109 -0.696628 -0.476275  5  3.0
2020-01-09  0.322251 -0.423799 -0.186723  5  4.0
2020-01-10  1.068257  1.071434 -1.918984  5  5.0

In [59]:
df2 = df.copy()

In [60]:
df2

A         B         C  D    F
2020-01-05  0.000000  0.000000 -0.967297  5  NaN
2020-01-06  0.054096 -1.846216 -1.273814  5  1.0
2020-01-07  0.391069 -0.654764  0.883613  5  2.0
2020-01-08 -0.403109 -0.696628 -0.476275  5  3.0
2020-01-09  0.322251 -0.423799 -0.186723  5  4.0
2020-01-10  1.068257  1.071434 -1.918984  5  5.0

In [61]:
df2[df2 > 0] = -df2
df2

A         B         C  D    F
2020-01-05  0.000000  0.000000 -0.967297 -5  NaN
2020-01-06 -0.054096 -1.846216 -1.273814 -5 -1.0
2020-01-07 -0.391069 -0.654764 -0.883613 -5 -2.0
2020-01-08 -0.403109 -0.696628 -0.476275 -5 -3.0
2020-01-09 -0.322251 -0.423799 -0.186723 -5 -4.0
2020-01-10 -1.068257 -1.071434 -1.918984 -5 -5.0